### ISSUE TITLE
Error create teams from group. Team Visibility can not be specified as it is inherited from the group.

### ISSUE THREAD

**Issue by aldvintumbelaka** [microsoftgraph/microsoft-graph-docs#10774]
Hi,

I use this API for quite a while already and works totally fine.
But just today, I suddenly got an issue with this API.
When I request for a new teams from group, it throw this error.

Failed to execute Templates backend request CreateTeamFromGroupWithTemplateRequest. Request Url: https://teams.microsoft.com/fabric/apac/templates/api/groups/f531e306-63c5-41cc-b962-3d222387246f/team, Request Method: PUT, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: max-age=2592000\r\nx-operationid: bbb294ddb3c7384c8eae43b92b3a4ba2\r\nx-telemetryid: 00-bbb294ddb3c7384c8eae43b92b3a4ba2-2aadb2d77d250743-00\r\nX-MSEdge-Ref: Ref A: 23558B2C936144998C16C5114089668F Ref B: SG2EDGE0920 Ref C: 2020-11-23T02:21:01Z\r\nDate: Mon, 23 Nov 2020 02:21:00 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"Team Visibility can not be specified as it is inherited from the group.\"}],\"operationId\":\"bbb294ddb3c7384c8eae43b92b3a4ba2\"}

Here is my full request URI and body.
![image](https://user-images.githubusercontent.com/33532350/99924712-e913b480-2d6d-11eb-9730-159691848b5f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darioroig** [comment]
Hi! We have the same problem. We used to create teams with the standard template, but today it shows us the error "Team Visibility can not be specified as it is inherited from the group."
The documentation indicates that the standard template should not have the properties set:
https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates
Regards

**Comment by mateusz-orlowski** [comment]
I have the same issue. I workaround it by calling PUT https://graph.microsoft.com/v1.0/groups/$groupId/team
with empty JSON body {}

**Comment by spplante** [comment]
Same thing here, it's been working flawlessly for weeks so it seems like a production breaking change

**Comment by steftacc** [comment]
Hello.
Same issue, we have been creating groups for several months with educationClass teamsTemplates:
                AdditionalData = new Dictionary<string, object>()
                {
                    { "template@odata.bind", "https://graph.microsoft.com/beta/teamsTemplates('educationClass')"},
                    {"group@odata.bind", $"https://graph.microsoft.com/v1.0/groups('{groupId}')"}
                },
but today we get same error message !

**Comment by DanaL** [comment]
To add another voice, we've had a service running to create Teams that has mostly been working fine and now today are receiving the same error message "Team Visibility can not be specified as it is inherited from the group".

Our particular case is a service written in C# using the Microsoft Graph library from NuGet and we get the error whether we are adding a Team on top of a Group.

**Comment by sebfil** [comment]
Same issue here, it's been working for months so far, and now over 2.500 schools can't create new teams... So this is a critical issue in production!!!

**Comment by MarMic1** [comment]
We got the same error message.

Beta Api -> not working
v1.0 Api -> not working
Graph Explorer -> not working 

This is a major issue. 1000 Tenants can't create new Teams with TeamsTemplate.

**Comment by olivermue** [comment]
We used this interface also regulary for several customer tenants without any problems. But we got this error now:

```
POST https://graph.microsoft.com/v1.0/teams
{
    "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
    "displayName": "My Team Template Test",
    "description": "Some description"
}
```
Returns
```
{
    "error": {
        "code": "BadRequest",
        "message": "Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/emea/templates/api/team, Request Method: POST, Response Status Code: BadRequest\r\n, ErrorMessage : {\"errors\":[{\"message\":\"'Team Definition. Visibility' should be equal to 'HiddenMembership'.\"}]}"
    }
}
```

After changing the request as follows:
```
{
    "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
    "displayName": "My Team Template Test",
    "description": "Some description",
    "visibility": "HiddenMembership"
}
```
we got the following error:
```
Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/emea/templates/api/team, Request Method: POST, Response Status Code: BadRequest, ErrorMessage : {\"errors\":[{\"message\":\"Team Visibility must be one of known types: [Private,Public,HiddenMembership].\"}]}
```

**Comment by S1m0nD** [comment]
I have the same Issue please fix it. Its a critical issue in production!!!

**Comment by MFI-designe** [comment]
We have same behavior than the other authors. Please find a solution for this problem.

**Comment by Amine0907** [comment]
We have a same problem and it's critical issue because we used it in multiple tenants and all are in error

**Comment by StephHardy** [comment]
We also have this issue, so production is crashing right now. Please fix it asap.

**Comment by aMo19AC** [comment]
Same issue. Please fix it.

**Comment by kbankham** [comment]
We have the same issue, so we have to temporarily disable our service . Please fix it.

**Comment by jamierushton** [comment]
Is anybody else able to confirm if this has been resolved.  So far I've managed to create 2 new teams via functional tests.

**Comment by sebfil** [comment]
> Is anybody else able to confirm if this has been resolved. So far I've managed to create 2 new teams via functional tests.

We are still checking, it looks like it is fixed... Update in a minute...

**Comment by aldvintumbelaka** [comment]
Hi, looks like this issue is now resolved. I'm closing this issue now.

**Comment by sebfil** [comment]
It looks like, that it is only fixed for user interactions, not for applications that calls the API. When adding Owners, it throws still same exception!

**Comment by aldvintumbelaka** [comment]
> It looks like, that it is only fixed for user interactions, not for applications that calls the API. When adding Owners, it throws still same exception!

Did you use this API to add owners? /teams/{team-id}/members

**Comment by sebfil** [comment]
> > It looks like, that it is only fixed for user interactions, not for applications that calls the API. When adding Owners, it throws still same exception!
> 
> Did you use this API to add owners? /teams/{team-id}/members

No, for applications this call is not successful (from documentation):

POST https://graph.microsoft.com/v1.0/teams
Content-Type: application/json

{
   "template@odata.bind":"https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
   "displayName":"My Sample Team",
   "description":"My Sample Team’s Description",
   "members":[
      {
         "@odata.type":"#microsoft.graph.aadUserConversationMember",
         "roles":[
            "owner"
         ],
         "userId":"0040b377-61d8-43db-94f5-81374122dc7e"
      }
   ]
}

**Comment by olivermue** [comment]
Unfortunately this problem is NOT fixed (at least not complete).

If you make the following request:
```
POST https://graph.microsoft.com/v1.0/teams
{
    "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
    "displayName": "My Team Template Test",
    "description": "Some description",
}
```
The request succeeds, you'll receive within the response header an `location` where you can check the current state of the creation process. So far so good.

BUT if you try the following request:
```
POST https://graph.microsoft.com/v1.0/teams
{
    "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
    "displayName": "My Team Template Test",
    "description": "Some description",
    "members": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "roles": [
                "owner"
            ],
            "userId": "<valid user id>"
        }
    ]
}
```
You'll get back the same error as before.

So it is currently not possible to create a team with a predefined owner.

**Comment by glissmam** [comment]
Same, the issue still exists:

Request
POST https://graph.microsoft.com/v1.0/teams
{
  "group@odata.bind": "https://graph.microsoft.com/v1.0/groups('...')",
  "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('standard')"
}

Response:
{
  "error": {
    "code": "BadRequest",
    "message": "Failed to execute Templates backend request CreateTeamFromGroupWithTemplateRequest. Request Url: https://teams.microsoft.com/fabric/emea/templates/api/groups/.../team, Request Method: PUT, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: Date: Tue, 24 Nov 2020 15:31:01 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"Team Visibility can not be specified as it is inherited from the group.\"}],"}",
    "innerError": {
      "date": "2020-11-24T15:31:01"
    }
  }
}

**Comment by Amine0907** [comment]
I've found a workaround by following these steps :

1. Create group POST https://graph.microsoft.com/v1.0/groups
2. PUT request to create Teams https://graph.microsoft.com/v1.0/groups/{id}/team this first call will generate an error due to replication delay)
3. Implement a retry pattern with the same request (PUT request) with a 10 seconds delay.

**Comment by fabianwilliams** [comment]
I have followed up on this item with the PM and they indicate that a Hotfix is underway and should be deployed within 6 hours. If the issue presents itself afterwards please tag me and I will follow up. Thank you for your patience. Cheers.

**Comment by olivermue** [comment]
Just tested this morning and I can say, that the "old way" by using the beta API to create a team with a template works again. Don't know, how many ways exists to do these things, but here is our current request, that works now (again).
```
POST https://graph.microsoft.com/beta/teams
{
    "displayName": "My Group Name",
    "description": "Some description",
    "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('educationClass')",
    "owners@odata.bind": [
        "https://graph.microsoft.com/beta/users('<someValidUserId>')"
    ]
}
``´

I think this will be just an intermediate state and when the bugs are fixed, they will publish the new version again and this kind of creation will fail again, but if in this case the v1.0 documented way will work this wouldn't be a big problem. But being informed BEFORE there roll-out starts would be great.

**Comment by fabianwilliams** [comment]
as well @olivermue  -- you are aware you can call v.1 /teams and pass a group that already exists to apply a Teams Template too... check it.. 
![CreateTeamFromGroupV1POST](https://user-images.githubusercontent.com/5719022/100240914-2492b800-2f01-11eb-90b5-7c0e26f91463.png)
returns
![CreateTeamFromGroupV1POSTReturn](https://user-images.githubusercontent.com/5719022/100241011-3ecc9600-2f01-11eb-9f3d-cd2178b152af.png)

**Comment by hellriser4** [comment]
Hi,

Creating teams with defaults templates will work. Not with Custom Templates : 

POST request :
{
"template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('CustomTemplateguid')";,
"displayName": "test",
"description": "test",
"visibility": "Private",
"channels": [
{"displayName":"Test1","isFavoriteByDefault":true,"description":"Test1."},
{"displayName":"Test2","isFavoriteByDefault":true,"description":"Test2."}
]
}

Callback
{
"error": {
"code": "BadRequest",
"message": "Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/amer/templates/api/team, Request Method: POST, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: max-age=2592000\r\nx-operationid: 747605855f81eb44a57cb6531357b059\r\nx-telemetryid: 00-747605855f81eb44a57cb6531357b059-a6f1c8f90dee0b4e-00\r\nX-MSEdge-Ref: Ref A: 846D93705DBB4194AD974B5A9913974D Ref B: BLUEDGE0219 Ref C: 2020-11-24T13:30:05Z\r\nDate: Tue, 24 Nov 2020 13:30:04 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"A template with id '1e1d8ca0-e3f5-470c-9c1f-df5f96628857' and locale 'en-US' could not be found.\"}],\"operationId\":\"747605855f81eb44a57cb6531357b059\"}",
"innerError": {
"date": "2020-11-24T13:30:05",
"request-id": "3fbf9c58-b233-4fae-a53b-d8ff6a92bd54",
"client-request-id": "985ba9db-becc-e560-5ec4-19e2e60383f5"
}
}
}

**Comment by sebfil** [comment]
@fabianwilliams - you can apply a template for existing groups, but you can't apply a educationClass template for an existing group. It throws an exception as fas as I know. So the background is, that edcationClass Teams based on "special" groups, that have education properties, and therefore you can't apply a tempalte with your suggested way...

**Comment by olivermue** [comment]
@fabianwilliams 
Thanks for the info. I think this is going to be little bit out of focus of this issue. ;-)

Nevertheless, while this approach works in general, it doesn't work (AFAIK) to get all features of an education class into an existing group. Especially some features of the OneNote course notebook and education assignments won't work if you try to apply a template later to a group. Maybe things have already being changed about this issue (or will be, when the latest version will be roll-out again), but currently we see a group as doomed if it can't be created by a template, due to the different behaviour.
