### ISSUE TITLE
Webhook Cancellation with HttpStatus Code 422 Not Working

### ISSUE THREAD

**Issue by jchilde** [microsoftgraph/microsoft-graph-docs#1417]
I am using C# Http Azure Function as my Microsoft Graph Webhook Receiver.

I am able to use the .net API to subscribe and unsubscribe; however, this is multi-tenant and since the webhook notification doesn't send a tenant id, I need a way to cancel subscriptions that are no longer tracked.

I know that a 3 day renewal is in place that would clean things up, but I want to reduce traffic.

So, if I no longer want a subscription, I return this HttpResponseMessage:
`return req.CreateResponse((HttpStatusCode)422);`

However, I am then greated with 4 more webhooks, and all future updates to the resource also trigger webhooks.

Your documentation says returning a 422 status code will cancel the subscription.  I think the process is not working.

**Comment by SomeshChandra-MSFT** [comment]
We are investigating the issue. Would you have approximate time range when you sent a 422 response for a notification?
Also I wanted to understand the scenario about getting tenantId in notifications. Could you please provide an example of how this will be useful to your scenario?

**Comment by jchilde** [comment]
The Time was June 14 at 2:05 PM UTC.

I am trying to keep a SharePoint Table in sync with a group calendar using Delta Queries and an Azure Function.  The creation of the web hook subscription is initiated by the end user using the end user’s authentication context.

When I need to remove the web hook subscription (typically because the end user deleted the list or subsite that is being synchronized) I can obviously execute a call against Microsoft Graph to remove the subscription; however, that call has to be authenticated with a user context (vice app only) because the resource is a Unified Group. I won’t have a user context when I need to cancel the subscription.

NOTE: App only context can be used to create a group, but all other navigation properties under the group endpoint require a user context.

So, rather than just ignoring the traffic, I thought that a 422 status code would solve the problem.

Unfortunately, a 422 status code does not appear to be cancelling the subscription as stated in MS documentation.

**Comment by SomeshChandra-MSFT** [comment]
We have identified the issue and will be rolling out a fix in next few weeks. I'll update this thread when the fix is available everywhere.

**Comment by SomeshChandra-MSFT** [comment]
The fix was deployed earlier this month.

**Comment by VSilantyev** [comment]
It is still not working at least for Mail subscriptions

**Comment by Savageman** [comment]
I just got this issue too.
I was able to find which user was subscribed, found its current token in my application and called `DELETE  https://graph.microsoft.com/v1.0/subscriptions/<subscription_id>` to clear it.

**Comment by piotrci** [comment]
@Savageman , @VSilantyev , @jchilde apologies but we have a regression for this functionality. we are planning to deploy a fix by 9/14/2018.
In the meantime, the workaround is to call `DELETE` as mentioned by @Savageman

**Comment by Savageman** [comment]
I still have the issue. I was able to find the user account, but was unable to `DELETE` the subscription, because both my access token and refresh tokens were expired.

It appears the HTTP 422 response code is no longer documented at https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/subscription_post_subscriptions

Would it be possible to call the `DELETE` endpoint using an Application-level permission token? It makes sense to be able to remove our own realtime subscription without having a user token.

**Comment by venkateshchepuru** [comment]
Correct. Deleting subscription with HTTP 422 response code is no longer supported. 

I will be very happy to dive into know more information on where your DELETE request is actually failing. Please share your client-request-id and UTC time stamp of the call.

If the subscription is created with Delegated (App+User ) context then we do not support the subscription deletion with just App Only token.

**Comment by Savageman** [comment]
Thanks for the fast reply 👍 

> Correct. Deleting subscription with HTTP 422 response code is no longer supported.

Bummer

> I will be very happy to dive into know more information on where your DELETE request is actually failing. 

It's not, it just happens I don't have any valid token anymore. I'll only keep receiving those push notifications for a few days, though it would be nice to be able to stop them, since I don't use them anymore.

> If the subscription is created with Delegated (App+User ) context then we do not support the subscription deletion with just App Only token.

Is there something I can do / somewhere I should ask to consider this as a feature request?

**Comment by venkateshchepuru** [comment]
As per the conversation I had with my team, we do not plan to support the scenario (App Deleting the subscription created by User). Thank you.
