### ISSUE TITLE
Unable to filter with endswith

### ISSUE THREAD

**Issue by thejazz15** [microsoftgraph/microsoft-graph-docs#4331]
To filter Microsoft Graph API responses, the docs suggest to use the `filter` query option. 

Here I've used `startswith` and `endswith` string functions on the `'/me/messages'` endpoint.

    query = {
        '$filter': "
          startswith(from/emailAddress/address, 'abcd')
          or endswith(from/emailAddress/address, 'gmail.com')"
      }

Only using `startswith` returns the expected response. On adding the `endswith` function to the filter query, the response received is an error.

    {
      "error": {
        "code": "ErrorInvalidUrlQueryFilter",
        "message": "The query filter contains one or more invalid nodes.",
        "innerError": {
          "request-id": "0d12e1f6-6105-4826-9656-8613f8c167ed",
          "date": "2019-03-14T11:05:56"
        }
      }
    }

**Comment by cendern** [comment]
They haven't implemented the full OData spec (and probably never will) so the `endswith` option to `filter` is not currently supported for any of their endpoints.

From [the docs](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter): "The startswith string operator is often supported. The any lambda operator is supported for some APIs."

Read that as "The only `filter` options that we've implemented are `startswith` and `any`, and even then their use is limited to a subset of endpoints".

It would be nice if they could also list the endpoints on which those options were valid, but you don't get to >600 open issues if you have a properly sized staff that actually fixes problems.

**Comment by Idlefisher** [comment]
Despite many upvotes in UserVoice, the filters like "endswith" are still unsupported. For example, even if the latest Microsoft doc( updated on 10/06/2020)  itself says the 'endswith' filter works for the /user endpoint, it is just not true. The given example doesn't work at all,  "Unsupported query" is still/simply returned by both 1.0 and beta endpoints. Trying it on various tenants, the same. Could the MS product team put their feet in the shoes of those who are doing daily admin job in very large organizations?

> Get all users with mail domain equal to 'hotmail.com' | https://graph.microsoft.com/v1.0/users?$count=true&$filter=endsWith(mail,'@hotmail.com')

**Comment by metahumantobe** [comment]
It has been more than one year since this issue is raised but still this 'endswith' query parameter issue has not resolved. I have started using this OData query parameter but forun out there are many limitations and when tried to search user from organization it doesn't work at all. Can anyone from the team provide a quick permanent fix to this issue ?

**Comment by baumannalexj** [comment]
bumping

**Comment by Kranf99** [comment]
still waiting for "endsWith" to work!

**Comment by baumannalexj** [comment]
@thejazz15 @cendern did you guys find a work around?

**Comment by baumannalexj** [comment]
what about using $search?
* https://docs.microsoft.com/en-us/graph/query-parameters#search-parameter
* $search is more flexible https://stackoverflow.com/a/50949710/6791342

someone want to try to master the query language for this?

**Comment by thejazz15** [comment]
@baumannalexj Unfortunately, we changed plans and started working on alternatives without using their graph API. Haven't revisited this issue since then.

**Comment by knguyen4221** [comment]
Hey folks.

Was working on this with my team and they got the endswith filter to work:

https://graph.microsoft.com/v1.0/users?$count=true&$filter=endsWith(mail,'some mail')

**Comment by knguyen4221** [comment]
I lied. They hotfixed it today.

**Comment by baumannalexj** [comment]
@knguyen4221 thank you for following up!
Great to hear.

**Comment by progMorten** [comment]
How come the endsWith works in the official example in graph explorer, but when I try to use it for the same in my AD, it gives bad request? applying it to the users :s I am doing it literally 100 % as in the example, but on my own user ad with mail properties.

Official working example: 
https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DendsWith(mail%2C%27%40hotmail.com%27)%26%24select%3Did%2CdisplayName%2Cmail&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d

**Comment by baumannalexj** [comment]
> How come the endsWith works in the official example in graph explorer, but when I try to use it for the same in my AD, it gives bad request? applying it to the users :s I am doing it literally 100 % as in the example, but on my own user ad with mail properties.
> 
> Official working example:
> https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DendsWith(mail%2C%27%40hotmail.com%27)%26%24select%3Did%2CdisplayName%2Cmail&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d


@progMorten to clarify: are you searching for users with `endwith(mail, hotmail.com)` verbatim, i.e. do you have `hotmail.com` emails in your AD. 

`endsWith` is working as expected for me, your issue might be better for a new thread.

**Comment by saikrishnans** [comment]
![image](https://user-images.githubusercontent.com/31478450/104910376-aa336100-59a2-11eb-9d4b-f90713307751.png)

How come its working for you guys, still am getting the same error.

**Comment by progMorten** [comment]
> > How come the endsWith works in the official example in graph explorer, but when I try to use it for the same in my AD, it gives bad request? applying it to the users :s I am doing it literally 100 % as in the example, but on my own user ad with mail properties.
> > Official working example:
> > https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DendsWith(mail%2C%27%40hotmail.com%27)%26%24select%3Did%2CdisplayName%2Cmail&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d
> 
> @progMorten to clarify: are you searching for users with `endwith(mail, hotmail.com)` verbatim, i.e. do you have `hotmail.com` emails in your AD.
> 
> `endsWith` is working as expected for me, your issue might be better for a new thread.

Hi, Sorry did not mean to hijack your thread :)

I solved this yesterday after some frustration, I was copying the query from the functioning example, into a "new" query in a new tab and I could not understand why it didnt work when it was exactly the same.

BUT: What I missed is that I need to add the ConsistencyLevel = eventual, it is already added in the example url, but of course its not there in my request when I started "new. So adding this made it work for me, both in browser and in c# using the graphserviceclient :) 

Maybe it helps some :)

![image](https://user-images.githubusercontent.com/29375412/104910853-400ec200-598a-11eb-9519-d5a695a21b6f.png)

![image](https://user-images.githubusercontent.com/29375412/104910913-59177300-598a-11eb-9d2c-d5c45d41f324.png)

**Comment by baumannalexj** [comment]
@progMorten no worries, just thought you'd get more traction :]

That's good to know, I've never used that header. Thanks!

**Comment by colmardev** [comment]
I always get Request__UnsupportedQuery_ filtering by `endsWith`, keeping default value `eventual `on `ConsistencyLevel `header.
Working with graph-explorer against AAD B2c.
Could be a B2C limitation?

Thanks in advance
![GRAPH Explorer FILTER endsWith ERROR](https://user-images.githubusercontent.com/57058314/104947433-0c4c9000-59bc-11eb-9961-eca1aa56a349.png)

**Comment by saikrishnans** [comment]
> I always get Request__UnsupportedQuery_ filtering by `endsWith`, keeping default value `eventual `on `ConsistencyLevel `header.
> Working with graph-explorer against AAD B2c.
> Could be a B2C limitation?
> 
> Thanks in advance
> ![GRAPH Explorer FILTER endsWith ERROR](https://user-images.githubusercontent.com/57058314/104947433-0c4c9000-59bc-11eb-9961-eca1aa56a349.png)

![image](https://user-images.githubusercontent.com/31478450/105005279-875e8680-5a4e-11eb-8287-48c37d7091d2.png)

When we are using the query param count=true getting at least the result. If there is a limitation it should show that in the error.

**Comment by craig-martin** [comment]
I've found that endsWith works on some properties (mail for example) but not on others (displayName for example)

**Comment by FaithOmbongi** [comment]
As @craig-martin has pointed out, not all parameters support **endsWith**, or the other OData query parameters. In addition, **startsWith** and **endsWith** are not interchangeable against the property. To verify that a property supports a specific OData query parameter, kindly refer to the API's main resource page.
